# general settings
name: LOLv2_real
model_type: MambaLLIE
scale: 1
num_gpu: 2
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: LLIE
    name: LOLv2_real
    type: PairedImageDataset
    dataroot_gt:
      - /opt/data/private/Dataset/LOLv2/Real_captured/Train/Normal/
    dataroot_lq:
      - /opt/data/private/Dataset/LOLv2/Real_captured/Train/Low/
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: LOLv2_real
    type: PairedImageDataset
    dataroot_gt: /opt/data/private/Dataset/LOLv2/Real_captured/Test/Normal/
    dataroot_lq: /opt/data/private/Dataset/LOLv2/Real_captured/Test/Low/
    io_backend:
      type: disk

# network structures
network_g:
  type: MambaLLIE
  nf: 48
  img_size: 128
  d_state: 32
  depths: [1,2,2,2,2,1]
  embed_dim: 48
  mlp_ratio: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001] 

  mixing_augs:
    mixup: True
    mixup_beta: 1.2
    use_identity: True

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
