# general settings
name: SDSD_outdoor
model_type: MambaLLIE
scale: 1
num_gpu: 1
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_SDSDImage
    # interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_gt: /opt/data/private/Dataset/SDSD_indoor/outdoor_static_np/outdoor_static_np/GT/
    dataroot_lq: /opt/data/private/Dataset/SDSD_indoor/outdoor_static_np/outdoor_static_np/input
    train_size: [960, 512]
    cache_keys: ~
    cache_data: true
    padding: new_info
    testing_dir: MVI_0898,MVI_0928,MVI_0906,MVI_0975,MVI_1001,MVI_0997,MVI_1003,MVI_1026,MVI_1030,MVI_1032

    filename_tmpl: '{}'
    io_backend:
      type: disk

    N_frames: 5     # how many frames as a input.
    # data argument
    use_flip: true
    use_rot: true
    color: RGB
    
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4

    ### -------------Progressive training--------------------------
    # mini_batch_sizes: [8,5,4,2,1,1]             # Batch size per gpu   
    # iters: [92000,64000,48000,36000,36000,24000]
    # gt_size: 384   # Max patch size for progressive training
    # gt_sizes: [128,160,192,256,320,384]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 256x256---------
    mini_batch_sizes: [8]   
    iters: [300000]
    gt_size: 256   # gt_size > gt_sizes[0]表示crop gt_sizes[0]的图片
    gt_sizes: [256]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_SDSDImage
    dataroot_gt: /opt/data/private/Dataset/SDSD_indoor/outdoor_static_np/outdoor_static_np/GT/
    dataroot_lq: /opt/data/private/Dataset/SDSD_indoor/outdoor_static_np/outdoor_static_np/input
    cache_data: true
    N_frames: 5
    padding: new_info
    train_size: [960, 512]
    testing_dir: MVI_0898,MVI_0928,MVI_0906,MVI_0975,MVI_1001,MVI_0997,MVI_1003,MVI_1026,MVI_1030,MVI_1032


    io_backend:
      type: disk

# network structures
network_g:
  type: MambaLLIE
  nf: 48
  img_size: 128
  d_state: 32
  depths: [1,2,2,2,2,1]
  embed_dim: 48
  mlp_ratio: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]       
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001] 

  mixing_augs:
    mixup: True
    mixup_beta: 1.2
    use_identity: True

  total_iter: 150000
  warmup_iter: -1  # no warm up


  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
